/*
  Copyright (c) 2026 TidesDB Corp.

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; version 2 of the License.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA
*/
#include "ha_tidesdb.h"

/* libtidesdb version/feature header, generated by the engine's CMake from
   libtidesdb/src/tidesdb_version.h.in.  Provides TIDESDB_VERSION (the vendored
   libtidesdb release) plus the TIDESDB_HAVE_* compression feature defines. */
#include <tidesdb/tidesdb_version.h>

extern "C"
{
#define XXH_INLINE_ALL
#include <tidesdb/xxhash.h>
}

#include <ft_global.h>
#include <mysql/plugin.h>

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstring>
#include <memory>
#include <string>
#include <thread>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "key.h"
#include "sql_class.h"
#include "sql_priv.h"

/* server-free core modules, unit-tested standalone under test/ */
#include "src/core/cf_name.h"
#include "src/core/fts_score.h"
#include "src/core/fts_text.h"
#include "src/core/rir.h"
#include "src/core/row_format.h"
#include "src/core/sort_key.h"
#include "src/core/spatial.h"
#include "src/engine/ha_tidesdb_config.h"
#include "src/engine/ha_tidesdb_status.h"
#include "src/handler/ha_tidesdb_fts.h"
#include "src/handler/ha_tidesdb_internal.h"
#include "src/handler/ha_tidesdb_keycodec.h"
#include "src/handler/ha_tidesdb_lifecycle.h"
#include "src/handler/ha_tidesdb_spatial.h"
#include "src/handler/ha_tidesdb_txn.h"

/*
  Map TidesDB library error codes to MariaDB handler error codes.
  A commit-time write conflict maps to HA_ERR_LOCK_DEADLOCK so that MariaDB's
  deadlock-retry logic kicks in and applications retry automatically instead of
  receiving the opaque HA_ERR_GENERIC / ER_GET_ERRNO 1030.  Transient
  contention and memtable backpressure map instead to HA_ERR_LOCK_WAIT_TIMEOUT,
  which rolls back only the current statement rather than the whole transaction.
*/
int tdb_rc_to_ha(int rc, const char *ctx)
{
    switch (rc)
    {
        case TDB_SUCCESS:
            return 0;

        /* Transient concurrency errors -- mapped to deadlock so MariaDB
           rolls back the transaction and the application can retry. */
        case TDB_ERR_CONFLICT:
            return HA_ERR_LOCK_DEADLOCK;

        /* A galera applier brute-force aborted this local transaction so a higher-priority cluster
           write could apply.  From that point every operation on it, its commit included, returns
           TDB_ERR_TXN_ABORTED.  Surface it as a deadlock so the losing side rolls back and retries,
           the same outcome InnoDB produces for the same cross-node race. */
        case TDB_ERR_TXN_ABORTED:
            return HA_ERR_LOCK_DEADLOCK;

        /* The transaction outlived its timeout and the library aborted it; a lock-wait timeout is
           the closest server error and drives the same statement-level retry. */
        case TDB_ERR_TXN_EXPIRED:
            return HA_ERR_LOCK_WAIT_TIMEOUT;

        /* Lock wait timeout -- rolls back the current statement only
           (not the whole transaction), less disruptive than full deadlock. */
        case TDB_ERR_LOCKED:
            return HA_ERR_LOCK_WAIT_TIMEOUT;

        /* Soft memtable-capacity backpressure from the library (memtable,
           flush queue, or L0 backlog at its cap).  The library absorbs this
           through its own L0 admission policy and only returns it once its
           internal no-progress budget is spent, so by the time it reaches the
           plugin it is a transient signal to retry.  Map it to lock-wait-timeout,
           which is the accurate name here (not deadlock; nothing is locked). */
        case TDB_ERR_MEMORY_LIMIT:
            return HA_ERR_LOCK_WAIT_TIMEOUT;

        /* Hard out-of-memory.  Distinct from TDB_ERR_MEMORY_LIMIT above
           (a soft back-pressure signal); TDB_ERR_MEMORY means the
           allocator itself failed. */
        case TDB_ERR_MEMORY:
            sql_print_error("[TIDESDB] %s: TDB_ERR_MEMORY", ctx);
            return HA_ERR_OUT_OF_MEM;

        case TDB_ERR_NOT_FOUND:
            return HA_ERR_KEY_NOT_FOUND;

        case TDB_ERR_EXISTS:
            return HA_ERR_FOUND_DUPP_KEY;

        case TDB_ERR_READONLY:
            return HA_ERR_READ_ONLY_TRANSACTION;

        /* I/O and corruption errors -- table needs repair/recovery.
           matches InnoDB's mapping of DB_CORRUPTION to HA_ERR_CRASHED. */
        case TDB_ERR_IO:
            sql_print_error("[TIDESDB] %s: I/O error (TDB_ERR_IO)", ctx);
            return HA_ERR_CRASHED;

        case TDB_ERR_CORRUPTION:
            sql_print_error("[TIDESDB] %s: data corruption detected (TDB_ERR_CORRUPTION)", ctx);
            return HA_ERR_CRASHED;

        /* Row too large for the configured block/value size. */
        case TDB_ERR_TOO_LARGE:
            return HA_ERR_TO_BIG_ROW;

        /* Database handle invalid (closed or never opened). */
        case TDB_ERR_INVALID_DB:
            sql_print_error("[TIDESDB] %s: invalid database handle (TDB_ERR_INVALID_DB)", ctx);
            return HA_ERR_INTERNAL_ERROR;

        /* Invalid arguments -- programming error in the plugin. */
        case TDB_ERR_INVALID_ARGS:
            sql_print_error("[TIDESDB] %s: invalid arguments (TDB_ERR_INVALID_ARGS)", ctx);
            return HA_ERR_INTERNAL_ERROR;

        /* A commit returns TDB_ERR_UNKNOWN when the shared memtable's active
           try_ref retry budget is exhausted under heavy rotation contention --
           same family as TDB_ERR_CONFLICT from the caller's perspective.
           Map to HA_ERR_LOCK_DEADLOCK so MariaDB triggers its deadlock
           retry path instead of surfacing an opaque ER_GET_ERRNO 1030. */
        case TDB_ERR_UNKNOWN:
            return HA_ERR_LOCK_DEADLOCK;

        default:
            sql_print_warning("[TIDESDB] %s: unexpected TidesDB error rc=%d", ctx, rc);
            return HA_ERR_GENERIC;
    }
}

/* MariaDB data directory */
extern MYSQL_PLUGIN_IMPORT char mysql_real_data_home[];

/* Global TidesDB database handle */
tidesdb_t *tdb_global = NULL;
std::string tdb_path;

handlerton *tidesdb_hton;

static handler *tidesdb_create_handler(handlerton *hton, TABLE_SHARE *table, MEM_ROOT *mem_root);

/* File extensions -- TidesDB manages its own files */
static const char *ha_tidesdb_exts[] = {NullS};

/* ******************** System variables (global DB config) ******************** */

static ulong srv_flush_threads = 4;
static ulong srv_compaction_threads = 4;
static ulong srv_log_level = 0;                                      /* TDB_LOG_TRACE */
static ulonglong srv_block_cache_size = TIDESDB_DEFAULT_BLOCK_CACHE; /* 256M */
static ulong srv_max_open_sstables = 256;
static my_bool srv_log_to_file = 1; /* write TidesDB logs to file (default is yes) */
static ulonglong srv_log_truncation_at = 24ULL * 1024 * 1024; /* log file truncation size (24MB) */
static ulonglong srv_memtable_write_buffer_size = 256ULL * 1024 * 1024; /* 256MB */

/* Per-session TTL override (seconds).  0 = use table default. */
static MYSQL_THDVAR_ULONGLONG(ttl, PLUGIN_VAR_RQCMDARG,
                              "Per-session TTL in seconds applied to INSERT/UPDATE; "
                              "0 means use the table-level TTL option; "
                              "can be set with SET [SESSION] tidesdb_ttl=N or "
                              "SET STATEMENT tidesdb_ttl=N FOR INSERT",
                              NULL, NULL, 0, 0, ULONGLONG_MAX, 0);

/* Per-session skip unique check (for bulk loads where PK duplicates
   are known impossible).  Same pattern as MyRocks rocksdb_skip_unique_check. */
static MYSQL_THDVAR_BOOL(skip_unique_check, PLUGIN_VAR_RQCMDARG,
                         "Skip uniqueness check on primary key and unique secondary indexes "
                         "during INSERT.  Only safe when the application guarantees no "
                         "duplicates (e.g. bulk loads with monotonic PKs).  "
                         "SET SESSION tidesdb_skip_unique_check=1",
                         NULL, NULL, 0);

/* Per-session row-count threshold for the post-delete range compaction
   trigger.  Zero disables the feature.  When non-zero, the engine tracks
   the comparable min/max PK bytes touched by a single multi-row DELETE
   statement (the start_bulk_delete / end_bulk_delete envelope around
   range deletes) and, if the deleted row count is at least the threshold,
   calls tidesdb_compact_range on the primary CF over the touched range
   at end-of-statement to physically reclaim the freshly-tombstoned range
   without waiting for a structural compaction trigger.  Threshold avoids
   making small DELETEs pay synchronous compaction cost. */
static MYSQL_THDVAR_ULONGLONG(
    compact_after_range_delete_min_rows, PLUGIN_VAR_RQCMDARG,
    "If non-zero, after a multi-row DELETE statement that touches at least "
    "this many rows, call tidesdb_compact_range over the touched primary-key "
    "range to physically reclaim tombstoned space.  Default 0 disables the "
    "feature; set to 0 to keep the post-DELETE behavior unchanged",
    NULL, NULL, 0, 0, ULONGLONG_MAX, 1);

/* Per-session opt-in for single-delete semantics on the primary row CF.
   Secondary-index deletes always use tidesdb_txn_single_delete because
   each (col_values, pk) / (term, pk) / (hilbert, pk) composite is written
   exactly once per row lifetime and deleted exactly once -- the
   single-delete contract holds unconditionally for those.
   For the primary CF the contract is narrower, UPDATE ... SET non_pk_col
   writes tidesdb_txn_put(share->cf, data_key(pk), ...) with the same PK,
   producing a put-over-put, and REPLACE INTO / INSERT ... ON DUPLICATE
   KEY UPDATE on tables with no secondary indexes does the same via a
   silent overwrite.  Under either pattern, dropping a put+single-delete
   pair at compaction can re-expose an older put.  Enabling this variable
   is the caller's promise that the session does none of the above --
   typical insert-then-delete, log-style, append-only workloads. */
static MYSQL_THDVAR_BOOL(single_delete_primary, PLUGIN_VAR_RQCMDARG,
                         "Use single-delete semantics for the primary row CF on DELETE. "
                         "Caller promises no UPDATE on non-PK columns, no REPLACE INTO, "
                         "and no INSERT ... ON DUPLICATE KEY UPDATE on tables without "
                         "secondary indexes for this session.  Violating the contract may "
                         "re-expose older row versions after compaction.  Safe choice: "
                         "leave OFF unless the session is INSERT-and-DELETE only.  "
                         "SET SESSION tidesdb_single_delete_primary=1",
                         NULL, NULL, 0);

/* Session-level defaults for table options.
   These are used by HA_TOPTION_SYSVAR so that CREATE TABLE without
   explicit options inherits the session/global default.  Dynamic and
   session-scoped, matching InnoDB's innodb_default_* pattern. */

static const char *compression_names[] = {"NONE", "SNAPPY", "LZ4", "ZSTD", "LZ4_FAST", NullS};
static TYPELIB compression_typelib = {array_elements(compression_names) - 1, "compression_typelib",
                                      compression_names, NULL, NULL};

static MYSQL_THDVAR_ENUM(default_compression, PLUGIN_VAR_RQCMDARG,
                         "Default compression algorithm for new tables "
                         "(NONE, SNAPPY, LZ4, ZSTD, LZ4_FAST)",
                         NULL, NULL, 2 /* LZ4 */, &compression_typelib);

static MYSQL_THDVAR_BOOL(default_bloom_filter, PLUGIN_VAR_RQCMDARG,
                         "Default bloom filter setting for new tables", NULL, NULL, 1);

static const char *sync_mode_names[] = {"NONE", "INTERVAL", "FULL", NullS};
static TYPELIB sync_mode_typelib = {array_elements(sync_mode_names) - 1, "sync_mode_typelib",
                                    sync_mode_names, NULL, NULL};

static MYSQL_THDVAR_ULONGLONG(default_bloom_fpr, PLUGIN_VAR_RQCMDARG,
                              "Default bloom filter false positive rate for new tables "
                              "(parts per 10000; 100 = 1%%)",
                              NULL, NULL, 100, 1, 10000, 1);

static MYSQL_THDVAR_BOOL(default_keep_values_inline, PLUGIN_VAR_RQCMDARG,
                         "Default KEEP_VALUES_INLINE for new tables. When ON a table holds every "
                         "value in its klog whatever its size, ignoring the database "
                         "value_separation_threshold",
                         NULL, NULL, 0);

static MYSQL_THDVAR_ULONGLONG(default_btree_klog_block_size, PLUGIN_VAR_RQCMDARG,
                              "Default btree klog node block size in bytes for new tables.  "
                              "A node sized just above the block manager first-read window "
                              "costs a second read on every access, so the library default "
                              "of 4096 matches that window",
                              NULL, NULL, TIDESQL_DEFAULT_BTREE_KLOG_BLOCK_SIZE, 512, ULONGLONG_MAX,
                              1);

static MYSQL_THDVAR_ULONGLONG(default_l1_file_count_trigger, PLUGIN_VAR_RQCMDARG,
                              "Default L1 file count compaction trigger for new tables", NULL, NULL,
                              4, 1, 1024, 1);

static MYSQL_THDVAR_ULONGLONG(default_level_size_ratio, PLUGIN_VAR_RQCMDARG,
                              "Default level size ratio for new tables", NULL, NULL,
                              TIDESQL_DEFAULT_LEVEL_SIZE_RATIO, 2, 100, 1);

static MYSQL_THDVAR_ULONGLONG(default_min_levels, PLUGIN_VAR_RQCMDARG,
                              "Default minimum LSM-tree levels for new tables.  Matches "
                              "the TidesDB library default",
                              NULL, NULL, TIDESQL_DEFAULT_MIN_LEVELS, 1, 64, 1);

static MYSQL_THDVAR_ULONGLONG(default_dividing_level_offset, PLUGIN_VAR_RQCMDARG,
                              "Default dividing level offset for new tables.  Matches "
                              "the TidesDB library default",
                              NULL, NULL, TIDESQL_DEFAULT_DIVIDING_LEVEL_OFFSET, 0, 64, 1);

/* Tombstone-density compaction trigger (parts per 10000 -- 5000 = 0.50 ratio).
   When non-zero, after each flush the engine inspects level-1 SSTables and
   escalates compaction for any single SST whose tombstone count divided by
   entry count exceeds this ratio while having at least
   tombstone_density_min_entries entries.  Default 0 keeps the existing
   structural-trigger behavior. */
static MYSQL_THDVAR_ULONGLONG(default_tombstone_density_trigger, PLUGIN_VAR_RQCMDARG,
                              "Default tombstone-density compaction trigger ratio for new tables, "
                              "expressed as parts per 10000 (5000 = 0.50, 0 disables).  When set, "
                              "compaction is escalated for any level-1 SSTable whose tombstone "
                              "count divided by entry count exceeds the ratio",
                              NULL, NULL, 0, 0, 10000, 1);

static MYSQL_THDVAR_ULONGLONG(default_tombstone_density_min_entries, PLUGIN_VAR_RQCMDARG,
                              "Minimum entry count for an SSTable to be considered by the "
                              "tombstone-density trigger; smaller SSTables are ignored",
                              NULL, NULL, 1024, 0, ULONGLONG_MAX, 1);

static const char *isolation_level_names[] = {
    "READ_UNCOMMITTED", "READ_COMMITTED", "REPEATABLE_READ", "SNAPSHOT", "SERIALIZABLE", NullS};
static TYPELIB isolation_level_typelib = {array_elements(isolation_level_names) - 1,
                                          "isolation_level_typelib", isolation_level_names, NULL,
                                          NULL};

static MYSQL_THDVAR_ENUM(default_isolation_level, PLUGIN_VAR_RQCMDARG,
                         "Default isolation level for new tables "
                         "(READ_UNCOMMITTED, READ_COMMITTED, REPEATABLE_READ, SNAPSHOT, "
                         "SERIALIZABLE)",
                         NULL, NULL, 2 /* REPEATABLE_READ */, &isolation_level_typelib);

static const char *log_level_names[] = {"TRACE", "INFO", "WARN", "ERROR", "NONE", NullS};
static TYPELIB log_level_typelib = {array_elements(log_level_names) - 1, "log_level_typelib",
                                    log_level_names, NULL, NULL};

static MYSQL_SYSVAR_ULONG(flush_threads, srv_flush_threads,
                          PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
                          "Number of TidesDB flush threads.  0 lets the library auto-size the "
                          "shared flush pool to min(CPU count, 4) at open",
                          NULL, NULL, 4, 0, 64, 0);

static MYSQL_SYSVAR_ULONG(compaction_threads, srv_compaction_threads,
                          PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
                          "Number of TidesDB compaction threads", NULL, NULL, 4, 1, 64, 0);

static MYSQL_SYSVAR_ENUM(log_level, srv_log_level, PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
                         "TidesDB log level (TRACE, INFO, WARN, ERROR, NONE)", NULL, NULL, 0,
                         &log_level_typelib);

static MYSQL_SYSVAR_ULONG(fts_min_word_len, srv_fts_min_word_len, PLUGIN_VAR_RQCMDARG,
                          "Minimum word length (in characters) for full-text indexing. "
                          "Shorter words are excluded from the index and search queries",
                          NULL, NULL, 3, 1, 84, 0);

static MYSQL_SYSVAR_ULONG(fts_max_word_len, srv_fts_max_word_len, PLUGIN_VAR_RQCMDARG,
                          "Maximum word length (in characters) for full-text indexing. "
                          "Longer words are excluded from the index and search queries",
                          NULL, NULL, 84, 1, 512, 0);

static MYSQL_SYSVAR_DOUBLE(fts_bm25_k1, srv_fts_bm25_k1, PLUGIN_VAR_RQCMDARG,
                           "BM25 k1 parameter controlling term-frequency saturation. "
                           "Higher values give more weight to repeated terms. "
                           "Standard default is 1.2",
                           NULL, NULL, 1.2, 0.0, 10.0, 0);

static MYSQL_SYSVAR_DOUBLE(fts_bm25_b, srv_fts_bm25_b, PLUGIN_VAR_RQCMDARG,
                           "BM25 b parameter controlling document-length normalization. "
                           "0 = no normalization, 1 = full normalization. "
                           "Standard default is 0.75",
                           NULL, NULL, 0.75, 0.0, 1.0, 0);

static MYSQL_SYSVAR_STR(fts_blend_chars, srv_fts_blend_chars,
                        PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_MEMALLOC,
                        "Characters treated as both separators and valid word characters "
                        "in full-text indexing.  When a blend character appears inside a "
                        "token, the tokenizer emits the full blended form plus each "
                        "sub-part on either side.  For example, with blend_chars=\"'\" "
                        "the input \"l'aria\" produces three tokens (l'aria, l, aria) "
                        "and the single-character \"l\" is then dropped by the default "
                        "tidesdb_fts_min_word_len=3.  Set to \"'\" for Italian/French "
                        "elision support.  Default is empty (no blend characters)",
                        NULL, tdb_fts_blend_chars_update, NULL);

static MYSQL_SYSVAR_STR(ft_stopword_table, srv_ft_stopword_table,
                        PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_MEMALLOC,
                        "User-defined stop word table in 'db_name/table_name' format. "
                        "The table must have a VARCHAR column named 'value'. "
                        "When NULL (default), uses the same default stop words as "
                        "information_schema.INNODB_FT_DEFAULT_STOPWORD. "
                        "Set to empty string to disable stop word filtering entirely",
                        NULL, tdb_ft_stopword_table_update, NULL);

static MYSQL_SYSVAR_ULONGLONG(block_cache_size, srv_block_cache_size,
                              PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
                              "TidesDB global block cache size in bytes", NULL, NULL,
                              TIDESDB_DEFAULT_BLOCK_CACHE, 0, ULONGLONG_MAX, 0);

static MYSQL_SYSVAR_ULONG(max_open_sstables, srv_max_open_sstables,
                          PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
                          "Max cached SSTable structures in LRU cache.  0 means unlimited, "
                          "bounded only by the process open-file limit",
                          NULL, NULL, 256, 0, 65536, 0);

static MYSQL_SYSVAR_BOOL(log_to_file, srv_log_to_file, PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
                         "Write TidesDB logs to a LOG file in the data directory "
                         "instead of stderr (default: ON)",
                         NULL, NULL, 1);

static MYSQL_SYSVAR_ULONGLONG(log_truncation_at, srv_log_truncation_at,
                              PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
                              "TidesDB log file truncation size in bytes "
                              "(0 disables truncation)",
                              NULL, NULL, 24ULL * 1024 * 1024, 0, ULONGLONG_MAX, 0);

static MYSQL_SYSVAR_ULONGLONG(memtable_write_buffer_size, srv_memtable_write_buffer_size,
                              PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
                              "Write buffer size in bytes for the memtable. "
                              "0 lets the library auto-size it",
                              NULL, NULL, 256ULL * 1024 * 1024, 0, ULONGLONG_MAX, 0);

static ulong srv_memtable_sync_mode = 2; /* FULL */

static MYSQL_SYSVAR_ENUM(memtable_sync_mode, srv_memtable_sync_mode,
                         PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
                         "Sync mode for the WAL.  "
                         "NONE relies on the OS page cache and is the fastest.  INTERVAL "
                         "syncs periodically on the memtable_sync_interval timer.  FULL "
                         "fsyncs on every commit and is the most durable.  This setting "
                         "governs WAL durability for every commit",
                         NULL, NULL, 2 /* FULL */, &sync_mode_typelib);

static ulonglong srv_memtable_sync_interval = 128000;

static MYSQL_SYSVAR_ULONGLONG(memtable_sync_interval, srv_memtable_sync_interval,
                              PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
                              "Sync interval in microseconds for the WAL "
                              "(only used when memtable_sync_mode=INTERVAL)",
                              NULL, NULL, 128000, 0, ULONGLONG_MAX, 0);

/* Skip-list tuning for the memtable.  The memtable is a single skiplist shared
   across the whole database, so its shape is a global knob rather than a per-table
   one.  Default 0 / 0.0 keeps the library default. */
static ulong srv_memtable_skip_list_max_level = 0;
static MYSQL_SYSVAR_ULONG(memtable_skip_list_max_level, srv_memtable_skip_list_max_level,
                          PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
                          "Skip-list max level for the memtable; 0 keeps the library default", NULL,
                          NULL, 0, 0, 32, 0);

static double srv_memtable_skip_list_probability = 0.0;
static MYSQL_SYSVAR_DOUBLE(
    memtable_skip_list_probability, srv_memtable_skip_list_probability,
    PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
    "Skip-list level promotion probability for the memtable; 0.0 keeps the library default", NULL,
    NULL, 0.0, 0.0, 1.0, 0);

/* Value-log segment size.  The value log seals its active segment at this size
   and opens a fresh one, which sets what a reclaim costs rather than the space
   the store settles at.  Zero keeps the library default of 256 MiB. */
static ulonglong srv_vlog_segment_size = 0;
static MYSQL_SYSVAR_ULONGLONG(
    vlog_segment_size, srv_vlog_segment_size, PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
    "Size in bytes at which the value log seals a segment and opens a fresh one; 0 keeps the "
    "library default",
    NULL, NULL, 0, 0, ULONGLONG_MAX, 0);

/* Database-level value separation threshold.  A value at or above this size is stored in the
   shared value log rather than inline in a column family's klog, so compaction rewrites only the
   key and a reference rather than the whole value on every merge.  This is db-wide in TidesDB 10;
   a single family can opt back to fully inline with the KEEP_VALUES_INLINE table option.  Zero
   keeps the library default. */
static ulonglong srv_value_separation_threshold = 0;
static MYSQL_SYSVAR_ULONGLONG(
    value_separation_threshold, srv_value_separation_threshold,
    PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
    "Values at or above this size in bytes are stored in the shared value log instead of inline in "
    "the klog; 0 keeps the library default",
    NULL, NULL, 0, 0, ULONGLONG_MAX, 0);

/* Sealed-memtable queue depth at which ingest is paced for backpressure.  A
   larger value spreads the throttle across a wider band before a hard stall,
   which helps a workload that opens many column families and rotates the shared
   memtable under load.  Zero keeps the library default of 16. */
static ulong srv_memtable_l0_queue_stall_threshold = 0;
static MYSQL_SYSVAR_ULONG(
    memtable_l0_queue_stall_threshold, srv_memtable_l0_queue_stall_threshold,
    PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
    "Sealed-memtable queue depth at which writes are paced for backpressure; 0 keeps the "
    "library default",
    NULL, NULL, 0, 0, 65535, 0);

/* Seconds of write inactivity after which the shared memtable is flushed even
   before it fills, so an idle database does not sit on unflushed data.  -1 keeps
   the library default. */
static int srv_memtable_idle_flush_seconds = -1;
static MYSQL_SYSVAR_INT(memtable_idle_flush_seconds, srv_memtable_idle_flush_seconds,
                        PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
                        "Seconds of write inactivity after which the shared memtable is flushed; "
                        "-1 keeps the library default",
                        NULL, NULL, -1, -1, 86400, 0);

/* Seconds a transaction may run before the library aborts it.  -1 keeps the
   library default. */
static longlong srv_txn_timeout_seconds = -1;
static MYSQL_SYSVAR_LONGLONG(txn_timeout_seconds, srv_txn_timeout_seconds,
                             PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
                             "Seconds a transaction may run before it is aborted; -1 keeps the "
                             "library default",
                             NULL, NULL, -1, -1, 2147483647, 0);

/* Configurable data directory.
   Defaults to NULL which means the plugin computes a sibling directory
   of mysql_real_data_home.  Setting this overrides the auto-computed path. */
static char *srv_data_home_dir = NULL;

static MYSQL_SYSVAR_STR(data_home_dir, srv_data_home_dir, PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_READONLY,
                        "Directory where TidesDB stores its data files; "
                        "defaults to <mysql_datadir>/../tidesdb_data; "
                        "must be set before server startup (read-only)",
                        NULL, NULL, NULL);

/* ******************** Online backup via system variable ******************** */

static char *srv_backup_dir = NULL;

static void tidesdb_backup_dir_update(THD *thd, struct st_mysql_sys_var *, void *var_ptr,
                                      const void *save)
{
    const char *new_dir = *static_cast<const char *const *>(save);

    if (!new_dir || !new_dir[0])
    {
        /* Empty string -- we just clear the variable */
        *static_cast<char **>(var_ptr) = NULL;
        return;
    }

    if (!tdb_global)
    {
        my_error(ER_UNKNOWN_ERROR, MYF(0), "TidesDB is not open");
        return;
    }

    /* Free the calling connection's TidesDB transaction before backup.
       tidesdb_backup() waits for all open transactions to drain.  The
       connection may still hold an open txn (created in external_lock
       but not yet committed).  If we don't free it here, the backup
       self-deadlocks waiting for our own txn. */
    {
        tidesdb_trx_t *trx = (tidesdb_trx_t *)thd_get_ha_data(thd, tidesdb_hton);
        if (trx && trx->txn)
        {
            tidesdb_txn_rollback(trx->txn);
            tidesdb_txn_free(trx->txn);
            trx->txn = NULL;
            trx->dirty = false;
            trx->txn_generation++;
            trx->fts_meta_pending.clear();
            trx->fts_meta_dirty = false;
        }
    }

    /* We copy the path before releasing the sysvar lock -- the save pointer
       is only valid while LOCK_global_system_variables is held. */
    std::string backup_path(new_dir);

    /* tidesdb_backup() spins waiting for all CF flushes to complete.
       The library's flush threads call sql_print_information() which
       internally acquires LOCK_global_system_variables.  This sysvar
       update callback is called WITH that mutex held, so tidesdb_backup()
       deadlocks (flush thread waits for lock, we wait for flush thread).
       Release the mutex around the blocking backup call. */
    mysql_mutex_unlock(&LOCK_global_system_variables);

    /* Backup started -- no log (user-triggered, success/failure reported via return code) */

    char *backup_path_c = const_cast<char *>(backup_path.c_str());
    int rc = tidesdb_backup(tdb_global, backup_path_c);

    mysql_mutex_lock(&LOCK_global_system_variables);

    if (rc != TDB_SUCCESS)
    {
        sql_print_error("[TIDESDB] Backup to '%s' failed (err=%d)", backup_path.c_str(), rc);
        my_printf_error(ER_UNKNOWN_ERROR, "[TIDESDB] Backup to '%s' failed (err=%d)", MYF(0),
                        backup_path.c_str(), rc);
        return;
    }

    /* For PLUGIN_VAR_MEMALLOC strings, the framework manages memory.
       We set var_ptr to the save value so the framework copies it. */
    *static_cast<const char **>(var_ptr) = new_dir;
}

static MYSQL_SYSVAR_STR(backup_dir, srv_backup_dir, PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_MEMALLOC,
                        "Set to a directory path to trigger an online TidesDB backup. "
                        "The directory must not exist or be empty. "
                        "Example: SET GLOBAL tidesdb_backup_dir = '/path/to/backup'",
                        NULL, tidesdb_backup_dir_update, NULL);

/* Checkpoint (hard-link snapshot) via system variable */

static char *srv_checkpoint_dir = NULL;

static void tidesdb_checkpoint_dir_update(THD *thd, struct st_mysql_sys_var *, void *var_ptr,
                                          const void *save)
{
    const char *new_dir = *static_cast<const char *const *>(save);

    if (!new_dir || !new_dir[0])
    {
        *static_cast<char **>(var_ptr) = NULL;
        return;
    }

    if (!tdb_global)
    {
        my_error(ER_UNKNOWN_ERROR, MYF(0), "TidesDB is not open");
        return;
    }

    /* A checkpoint is a durability barrier followed by a copy of the database to the requested
       path, so the checkpoint directory holds a self-contained snapshot with its own manifest and
       sstables that a restart or an external tool can open, not just an in-place fsync of the live
       database. */

    /* Free the calling connection's own transaction first, the same way the backup path does,
       because both the barrier and the copy drain open transactions and would otherwise wait on
       this connection's still-open txn. */
    {
        tidesdb_trx_t *trx = (tidesdb_trx_t *)thd_get_ha_data(thd, tidesdb_hton);
        if (trx && trx->txn)
        {
            tidesdb_txn_rollback(trx->txn);
            tidesdb_txn_free(trx->txn);
            trx->txn = NULL;
            trx->dirty = false;
            trx->txn_generation++;
            trx->fts_meta_pending.clear();
            trx->fts_meta_dirty = false;
        }
    }

    std::string checkpoint_path(new_dir);

    /* Both calls block on flush completion, and the library's flush threads log through
       sql_print_information which takes LOCK_global_system_variables, the mutex this update
       callback already holds, so release it around the blocking work to avoid a deadlock. */
    mysql_mutex_unlock(&LOCK_global_system_variables);

    int rc = tidesdb_checkpoint(tdb_global);
    if (rc == TDB_SUCCESS)
        rc = tidesdb_backup(tdb_global, const_cast<char *>(checkpoint_path.c_str()));

    mysql_mutex_lock(&LOCK_global_system_variables);

    if (rc != TDB_SUCCESS)
    {
        sql_print_error("[TIDESDB] Checkpoint to '%s' failed (err=%d)", checkpoint_path.c_str(),
                        rc);
        my_printf_error(ER_UNKNOWN_ERROR, "[TIDESDB] Checkpoint to '%s' failed (err=%d)", MYF(0),
                        checkpoint_path.c_str(), rc);
        return;
    }

    *static_cast<const char **>(var_ptr) = new_dir;
}

static MYSQL_SYSVAR_STR(checkpoint_dir, srv_checkpoint_dir,
                        PLUGIN_VAR_RQCMDARG | PLUGIN_VAR_MEMALLOC,
                        "Set to a directory path to trigger a TidesDB checkpoint "
                        "(hard-link snapshot, near-instant). "
                        "The directory must not exist or be empty. "
                        "Example: SET GLOBAL tidesdb_checkpoint_dir = '/path/to/checkpoint'",
                        NULL, tidesdb_checkpoint_dir_update, NULL);

static struct st_mysql_sys_var *tidesdb_system_variables[] = {
    MYSQL_SYSVAR(flush_threads),
    MYSQL_SYSVAR(compaction_threads),
    MYSQL_SYSVAR(log_level),
    MYSQL_SYSVAR(block_cache_size),
    MYSQL_SYSVAR(max_open_sstables),
    MYSQL_SYSVAR(backup_dir),
    MYSQL_SYSVAR(checkpoint_dir),
    MYSQL_SYSVAR(fts_min_word_len),
    MYSQL_SYSVAR(fts_max_word_len),
    MYSQL_SYSVAR(fts_bm25_k1),
    MYSQL_SYSVAR(fts_bm25_b),
    MYSQL_SYSVAR(ft_stopword_table),
    MYSQL_SYSVAR(fts_blend_chars),
    MYSQL_SYSVAR(data_home_dir),
    MYSQL_SYSVAR(ttl),
    MYSQL_SYSVAR(skip_unique_check),
    MYSQL_SYSVAR(single_delete_primary),
    MYSQL_SYSVAR(compact_after_range_delete_min_rows),
    MYSQL_SYSVAR(default_compression),
    MYSQL_SYSVAR(default_bloom_filter),
    MYSQL_SYSVAR(default_bloom_fpr),
    MYSQL_SYSVAR(default_keep_values_inline),
    MYSQL_SYSVAR(value_separation_threshold),
    MYSQL_SYSVAR(default_btree_klog_block_size),
    MYSQL_SYSVAR(default_l1_file_count_trigger),
    MYSQL_SYSVAR(default_level_size_ratio),
    MYSQL_SYSVAR(default_min_levels),
    MYSQL_SYSVAR(default_dividing_level_offset),
    MYSQL_SYSVAR(default_isolation_level),
    MYSQL_SYSVAR(log_to_file),
    MYSQL_SYSVAR(log_truncation_at),
    MYSQL_SYSVAR(memtable_write_buffer_size),
    MYSQL_SYSVAR(memtable_sync_mode),
    MYSQL_SYSVAR(memtable_sync_interval),
    MYSQL_SYSVAR(memtable_skip_list_max_level),
    MYSQL_SYSVAR(memtable_skip_list_probability),
    MYSQL_SYSVAR(vlog_segment_size),
    MYSQL_SYSVAR(memtable_l0_queue_stall_threshold),
    MYSQL_SYSVAR(memtable_idle_flush_seconds),
    MYSQL_SYSVAR(txn_timeout_seconds),
    MYSQL_SYSVAR(default_tombstone_density_trigger),
    MYSQL_SYSVAR(default_tombstone_density_min_entries),
    NULL};

/* ******************** Table options (per-table CF config) ******************** */

ha_create_table_option tidesdb_table_option_list[] = {
    /* Options with SYSVAR defaults inherit from session variables
       (e.g. SET SESSION tidesdb_default_bloom_filter=OFF).
       When not explicitly set in CREATE TABLE, the session default is used. */
    HA_TOPTION_SYSVAR("KEEP_VALUES_INLINE", keep_values_inline, default_keep_values_inline),
    HA_TOPTION_SYSVAR("BTREE_KLOG_BLOCK_SIZE", btree_klog_block_size,
                      default_btree_klog_block_size),
    HA_TOPTION_SYSVAR("LEVEL_SIZE_RATIO", level_size_ratio, default_level_size_ratio),
    HA_TOPTION_SYSVAR("MIN_LEVELS", min_levels, default_min_levels),
    HA_TOPTION_SYSVAR("DIVIDING_LEVEL_OFFSET", dividing_level_offset,
                      default_dividing_level_offset),
    HA_TOPTION_SYSVAR("BLOOM_FPR", bloom_fpr, default_bloom_fpr),
    HA_TOPTION_SYSVAR("L1_FILE_COUNT_TRIGGER", l1_file_count_trigger,
                      default_l1_file_count_trigger),
    HA_TOPTION_SYSVAR("COMPRESSION", compression, default_compression),
    HA_TOPTION_SYSVAR("ISOLATION_LEVEL", isolation_level, default_isolation_level),
    HA_TOPTION_SYSVAR("BLOOM_FILTER", bloom_filter, default_bloom_filter),
    HA_TOPTION_SYSVAR("TOMBSTONE_DENSITY_TRIGGER", tombstone_density_trigger,
                      default_tombstone_density_trigger),
    HA_TOPTION_SYSVAR("TOMBSTONE_DENSITY_MIN_ENTRIES", tombstone_density_min_entries,
                      default_tombstone_density_min_entries),
    HA_TOPTION_NUMBER("TTL", ttl, 0, 0, ULONGLONG_MAX, 1),
    HA_TOPTION_BOOL("ENCRYPTED", encrypted, 0),
    HA_TOPTION_NUMBER("ENCRYPTION_KEY_ID", encryption_key_id, 1, 1, 255, 1),
    HA_TOPTION_END};

/* ******************** Field options (per-column) ******************** */

ha_create_table_option tidesdb_field_option_list[] = {HA_FOPTION_BOOL("TTL", ttl, 0),
                                                      HA_FOPTION_END};

/* ******************** TidesDB_share ******************** */

TidesDB_share::TidesDB_share()
    : cf(NULL),
      has_user_pk(false),
      pk_index(0),
      pk_key_len(0),
      next_row_id(1),
      isolation_level(TDB_ISOLATION_REPEATABLE_READ),
      default_ttl(0),
      ttl_field_idx(TIDESDB_TTL_FIELD_NONE),
      encrypted(false),
      encryption_key_id(TIDESDB_DEFAULT_ENCRYPTION_KEY_ID),
      encryption_key_version(0),
      has_blobs(false),
      has_ttl(false),
      num_secondary_indexes(0)
{
    memset(idx_comp_key_len, 0, sizeof(idx_comp_key_len));
    memset(idx_is_fts, 0, sizeof(idx_is_fts));
    memset(idx_is_spatial, 0, sizeof(idx_is_spatial));
    for (uint i = 0; i < MAX_KEY; i++) cached_rec_per_key[i].store(0, std::memory_order_relaxed);
}

TidesDB_share::~TidesDB_share()
{
}

/* ******************** Plugin init / deinit ******************** */

static bool tidesdb_hton_flush_logs(handlerton *);
static int tidesdb_hton_panic(handlerton *, enum ha_panic_function flag);
static void tidesdb_hton_pre_shutdown(void);

static int tidesdb_init_func(void *p)
{
    DBUG_ENTER("tidesdb_init_func");

    tidesdb_hton = (handlerton *)p;
    tidesdb_hton->create = tidesdb_create_handler;
    /* We enforce foreign keys inside the engine, so advertise the capability.
       The server treats the flag as informational, the enforcement lives in the
       row operations and the catalog read-back methods. */
    tidesdb_hton->flags = HTON_SUPPORTS_FOREIGN_KEYS;
    tidesdb_hton->tablefile_extensions = ha_tidesdb_exts;
    tidesdb_hton->table_options = tidesdb_table_option_list;
    tidesdb_hton->field_options = tidesdb_field_option_list;
    tidesdb_hton->drop_table = tidesdb_hton_drop_table;
    tidesdb_hton->drop_database = tidesdb_hton_drop_database;

    /* transaction, savepoint, and connection-close callbacks plus the savepoint storage size */
    tidesdb_txn_register(tidesdb_hton);
    tidesdb_hton->show_status = tidesdb_show_status;

    /* Durability / lifecycle / cancellation hooks. */
    tidesdb_hton->flush_logs = tidesdb_hton_flush_logs;
    tidesdb_hton->panic = tidesdb_hton_panic;
    tidesdb_hton->pre_shutdown = tidesdb_hton_pre_shutdown;

#ifdef WITH_WSREP
    /* Advertise galera replication and wire the cluster-position checkpoint and brute-force-abort
       hooks so a table created with ENGINE=TIDESDB participates in a wsrep cluster. */
    tidesdb_wsrep_register(tidesdb_hton);
#endif

    /* Arm the full-text locks, seed the default stop words, and build the blend map. */
    fts_init();

    /* We use tidesdb_data_home_dir if set, otherwise compute
       a sibling directory of the MariaDB data directory. */
    if (srv_data_home_dir && srv_data_home_dir[0])
    {
        tdb_path = srv_data_home_dir;
        while (!tdb_path.empty() && tdb_path.back() == '/') tdb_path.pop_back();
    }
    else
    {
        std::string data_home(mysql_real_data_home);
        while (!data_home.empty() && data_home.back() == '/') data_home.pop_back();
        size_t slash_pos = data_home.rfind('/');
        if (slash_pos != std::string::npos)
            tdb_path = data_home.substr(0, slash_pos + 1) + "tidesdb_data";
        else
            tdb_path = "tidesdb_data";
    }

    static const int log_level_map[] = {TDB_LOG_TRACE, TDB_LOG_INFO, TDB_LOG_WARN, TDB_LOG_ERROR,
                                        TDB_LOG_NONE};

    tidesdb_config_t cfg = tidesdb_default_config();
    cfg.db_path = const_cast<char *>(tdb_path.c_str());
    cfg.num_flush_threads = (int)srv_flush_threads;
    cfg.num_compaction_threads = (int)srv_compaction_threads;
    cfg.log_level = (tidesdb_log_level_t)log_level_map[srv_log_level];
    cfg.block_cache_size = (size_t)srv_block_cache_size;
    cfg.max_open_sstables = (int)srv_max_open_sstables;
    cfg.log_to_file = srv_log_to_file ? 1 : 0;
    cfg.log_truncation_at = (size_t)srv_log_truncation_at;
    cfg.memtable_write_buffer_size = (size_t)srv_memtable_write_buffer_size;
    cfg.memtable_sync_mode = tdb_sync_mode_map[srv_memtable_sync_mode];
    cfg.memtable_sync_interval_us = (uint64_t)srv_memtable_sync_interval;
    cfg.memtable_skip_list_max_level = (int)srv_memtable_skip_list_max_level;
    cfg.memtable_skip_list_probability = (float)srv_memtable_skip_list_probability;
    /* cfg already carries the library defaults from tidesdb_default_config, so only
       override the value log segment size and the l0 stall threshold when the operator
       set them, keeping zero as the meaning follow the library. */
    if (srv_vlog_segment_size) cfg.vlog_segment_size = (size_t)srv_vlog_segment_size;
    if (srv_value_separation_threshold)
        cfg.value_separation_threshold = (size_t)srv_value_separation_threshold;
    if (srv_memtable_l0_queue_stall_threshold)
        cfg.memtable_l0_queue_stall_threshold = (int)srv_memtable_l0_queue_stall_threshold;
    if (srv_memtable_idle_flush_seconds >= 0)
        cfg.memtable_idle_flush_seconds = (int)srv_memtable_idle_flush_seconds;
    if (srv_txn_timeout_seconds >= 0) cfg.txn_timeout_seconds = (int64_t)srv_txn_timeout_seconds;

    int rc = tidesdb_open(&cfg, &tdb_global);
    if (rc != TDB_SUCCESS)
    {
        sql_print_error("[TIDESDB] Failed to open TidesDB at %s (err=%d)", tdb_path.c_str(), rc);
        DBUG_RETURN(1);
    }

    sql_print_information("[TIDESDB] TidesDB opened at %s", tdb_path.c_str());

    DBUG_RETURN(0);
}

/*
  Handlerton-level FLUSH LOGS callback.  Called on FLUSH LOGS and by
  mariadb-backup before copying files so the on-disk WAL is a consistent
  snapshot.  The write-ahead log is db-level in TidesDB 10, so a single
  tidesdb_sync_wal covers every column family.  Returns false on success
  (handlerton convention).
*/
static bool tidesdb_hton_flush_logs(handlerton *)
{
    if (!tdb_global) return false;

    /* the write-ahead log is db-level in TidesDB 10, so one sync covers every cf. */
    int rc = tidesdb_sync_wal(tdb_global);
    if (rc != TDB_SUCCESS)
    {
        sql_print_warning("[TIDESDB] flush_logs: tidesdb_sync_wal failed (rc=%d)", rc);
        return true; /* error */
    }
    return false;
}

/*
  Handlerton-level panic callback.  MariaDB calls this on signal-driven or
  abnormal shutdown paths where tidesdb_deinit_func may not run.  We only
  react to HA_PANIC_CLOSE -- the other flags are legacy ISAM-era.
*/
static int tidesdb_hton_panic(handlerton *, enum ha_panic_function flag)
{
    if (flag != HA_PANIC_CLOSE) return 0;

    if (tdb_global)
    {
        tidesdb_close(tdb_global);
        tdb_global = NULL;
    }
    return 0;
}

/*
  Handlerton-level pre_shutdown callback.  Runs before the deinit path so
  background threads that still need a fully-functional server (compaction,
  flush) get a clean signal to drain.  We flush the WAL synchronously
  and let tidesdb_close() in deinit finish the teardown.
*/
static void tidesdb_hton_pre_shutdown(void)
{
    if (!tdb_global) return;

    /* Sync the WAL so durability is preserved if deinit is racing
       a forced exit.  The call is cheap when there's nothing to sync. */
    (void)tidesdb_hton_flush_logs(tidesdb_hton);
}

static int tidesdb_deinit_func(void *p)
{
    DBUG_ENTER("tidesdb_deinit_func");

    if (tdb_global)
    {
        /* tidesdb_close performs the orderly teardown, flushing pending commits
           and quiescing the background workers. */
        tidesdb_close(tdb_global);
        tdb_global = NULL;
    }

    fts_deinit();

    sql_print_information("[TIDESDB] TidesDB closed");
    DBUG_RETURN(0);
}

/* ******************** path_to_cf_name ******************** */

std::string ha_tidesdb::path_to_cf_name(const char *path)
{
    return tidesdb::cf_name::to_cf_name(path);
}

/* ******************** Factory / Constructor ******************** */

static handler *tidesdb_create_handler(handlerton *hton, TABLE_SHARE *table, MEM_ROOT *mem_root)
{
    return new (mem_root) ha_tidesdb(hton, table);
}

/* Cache the per-statement session variables the write paths read on the hot loop, populated once
   per statement.  cached_thd_ and the valid flag are set in external_lock; THDVAR must be read here
   in the root translation unit where the MYSQL_THDVAR sysvars are defined, so the extracted DML
   translation units call this rather than reading THDVAR directly. */
void ha_tidesdb::cache_stmt_thdvars()
{
    if (cached_thdvars_valid_) return;
    cached_skip_unique_ = THDVAR(cached_thd_, skip_unique_check);
    cached_sess_ttl_ = THDVAR(cached_thd_, ttl);
    cached_single_delete_primary_ = THDVAR(cached_thd_, single_delete_primary);
    cached_compact_after_range_delete_min_rows_ =
        THDVAR(cached_thd_, compact_after_range_delete_min_rows);
    cached_thdvars_valid_ = true;
}

/* ******************** AUTO_INCREMENT (O(1) atomic counter) ******************** */

/*
  Override the default get_auto_increment() which calls index_last() on every
  single auto-commit INSERT.  That creates and destroys a TidesDB merge-heap
  iterator each time -- O(N sources).  Instead, we maintain an in-memory atomic
  counter on TidesDB_share that is seeded once from the table data at open time
  and atomically incremented thereafter -- O(1).
*/
void ha_tidesdb::get_auto_increment(ulonglong offset, ulonglong increment,
                                    ulonglong nb_desired_values, ulonglong *first_value,
                                    ulonglong *nb_reserved_values)
{
    DBUG_ENTER("ha_tidesdb::get_auto_increment");

    /* Atomic fetch-and-add -- each caller gets a unique range.
       The counter stores the last value that was handed out. */
    ulonglong cur = share->auto_inc_val.load(std::memory_order_relaxed);
    ulonglong next;
    do
    {
        next = cur + nb_desired_values;
    } while (!share->auto_inc_val.compare_exchange_weak(cur, next, std::memory_order_relaxed));

    *first_value = cur + 1;
    /*
      We reserve exactly what was asked for.  MariaDB's update_auto_increment()
      will call us again when the interval is exhausted.
    */
    *nb_reserved_values = nb_desired_values;

    DBUG_VOID_RETURN;
}

/*
  Reset the auto-increment counter(s) to the given value.  MariaDB's default
  truncate() path calls this after delete_all_rows, and ALTER TABLE ...
  AUTO_INCREMENT=N routes here as well.  The next auto-generated ID equals
  `value` itself, so we store `value - 1` (get_auto_increment does
  fetch-add and returns cur+1).  `value == 0` is the TRUNCATE case reset
  to 1.  Hidden-PK row-id gets the same treatment for consistency.
*/
int ha_tidesdb::reset_auto_increment(ulonglong value)
{
    DBUG_ENTER("ha_tidesdb::reset_auto_increment");
    if (!share) DBUG_RETURN(0);

    ulonglong new_val = value > 0 ? value - 1 : 0;
    share->auto_inc_val.store(new_val, std::memory_order_relaxed);

    /* Hidden PK row-ids are one-based (delete_all_rows stores
       HIDDEN_PK_FIRST_ROW_ID for empty tables).  Treat value==0 as restart. */
    uint64_t new_rowid = value > 0 ? (uint64_t)value : HIDDEN_PK_FIRST_ROW_ID;
    share->next_row_id.store(new_rowid, std::memory_order_relaxed);

    /* Persist an ALTER TABLE ... AUTO_INCREMENT=N so the raised start value survives a restart. */
    if (value > 1) write_auto_inc_meta(share->cf, value);

    DBUG_RETURN(0);
}

int ha_tidesdb::extra(enum ha_extra_function operation)
{
    switch (operation)
    {
        case HA_EXTRA_KEYREAD:
            keyread_only_ = true;
            break;
        case HA_EXTRA_NO_KEYREAD:
            keyread_only_ = false;
            break;
        case HA_EXTRA_WRITE_CAN_REPLACE:
            /* REPLACE INTO -- write_row may skip the dup-check and let
               tidesdb_txn_put overwrite silently.  Only safe when there
               are no secondary indexes (otherwise old index entries must
               still be cleaned up via delete+reinsert). */
            write_can_replace_ = true;
            break;
        case HA_EXTRA_INSERT_WITH_UPDATE:
            /* INSERT ON DUPLICATE KEY UPDATE -- the server needs write_row
               to return HA_ERR_FOUND_DUPP_KEY so it can switch to update_row. */
            break;
        case HA_EXTRA_WRITE_CANNOT_REPLACE:
            write_can_replace_ = false;
            break;
        case HA_EXTRA_PREPARE_FOR_DROP:
            /* Table is about to be dropped -- skip fsync overhead */
            break;
        default:
            break;
    }
    return 0;
}

static struct st_mysql_storage_engine tidesdb_storage_engine = {MYSQL_HANDLERTON_INTERFACE_VERSION};

maria_declare_plugin(tidesdb){MYSQL_STORAGE_ENGINE_PLUGIN,
                              &tidesdb_storage_engine,
                              "TidesDB",
                              "TidesDB",
                              "LSM-tree engine with ACID transactions, MVCC concurrency, "
                              "secondary/spatial/full-text/vector indexes, and encryption",
                              PLUGIN_LICENSE_GPL,
                              tidesdb_init_func,
                              tidesdb_deinit_func,
                              TIDESQL_VERSION_HEX,
                              tidesdb_status_variables,
                              tidesdb_system_variables,
                              TIDESQL_VERSION_STR,
                              MariaDB_PLUGIN_MATURITY_GAMMA} maria_declare_plugin_end;
